modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory (24 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="veggie_way" #mandatory
version="2.2.9" #mandatory
displayName="The Veggie Way" #mandatory
description='''
The veggie way to nutritious food without killing
'''


[[dependencies.veggie_way]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.veggie_way]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.16.4]"
    ordering="NONE"
    side="BOTH"
