modLoader="javafml" #mandatory

loaderVersion="[41,)" #mandatory

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="veggie_way" #mandatory
version="2.5.7" #mandatory
displayName="The Veggie Way" #mandatory
description='''
The veggie way to nutritious food without killing
'''


[[dependencies.veggie_way]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.veggie_way]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"
