modLoader="javafml" #mandatory

loaderVersion="[38,)" #mandatory (36 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="veggie_way" #mandatory
version="2.4.0" #mandatory
displayName="The Veggie Way" #mandatory
description='''
The veggie way to nutritious food without killing
'''


[[dependencies.veggie_way]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.veggie_way]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18]"
    ordering="NONE"
    side="BOTH"
